# Git commands
alias gclean='git clean -fd'
alias gpristine='git reset --hard && git clean -dfx'
alias gignore='git update-index --assume-unchanged'
alias gignored='git ls-files -v | grep "^[[:lower:]]"'
alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify -m "--wip-- [skip ci]"'
alias gwatch='git whatchanged -p --abbrev-commit --pretty=medium'

alias go='git checkout'
alias gom='git checkout master'
alias god='git checkout develop'

alias gb='git branch'
alias gbr='git branch --remote'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbo='git branch --orphan'
alias gbs='git bisect'
alias gbsb='git bisect bad'
alias gbsg='git bisect good'
alias gbsr='git bisect reset'
alias gbss='git bisect start'
alias ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'

alias gc='git commit'
alias gca='git commit -v -a'
alias gcm='git commit -m'
alias gcam='git commit -a -m'
alias gcsm='git commit -s -m'
alias gc!='git commit -v --amend'
alias gcn!='git commit -v --no-edit --amend'
alias gca!='git commit -v -a --amend'
alias gcan!='git commit -v -a --no-edit --amend'
alias gcans!='git commit -v -a -s --no-edit --amend'

alias ga='git add'
alias gaa='git add --all'
alias gapa='git add --patch'
alias gau='git add --update'
alias gav='git add --verbose'
alias gap='git apply'

alias gd='git diff'
alias gdca='git diff --cached'
alias gdcw='git diff --cached --word-diff'
alias gdct='git describe --tags `git rev-list --tags --max-count=1`'
alias gds='git diff --staged'
alias gdt='git diff-tree --no-commit-id --name-only -r'
alias gdw='git diff --word-diff'

alias gr='git remote'
alias gra='git remote add'

alias gl='git log'
alias glg='git log --stat'
alias glgp='git log --stat -p'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glgm='git log --graph --max-count=10'
alias glo='git log --oneline --decorate'

alias gf='git fetch'
alias gfa='git fetch --all --prune'
alias gfo='git fetch origin'

alias gp='git push'
alias gpd='git push --dry-run'
alias gpf='git push --force-with-lease'
alias gpo='git push origin --all && git push origin --tags'
alias gpu='git push upstream'
alias gpv='git push -v'
alias gpsup='git push --set-upstream origin $(git_current_branch)'

alias gup='git pull --rebase'
alias gupv='git pull --rebase -v'
alias gupa='git pull --rebase --autostash'
alias gupav='git pull --rebase --autostash -v'
alias glum='git pull upstream master'

alias gs='git status'
alias gss='git status -s'
alias gsb='git status -sb'
alias gsh='git show'

alias gm='git submodule'
alias gmi='git submodule init'
alias gmu='git submodule update'
alias gmuc='git submodule update --checkout'
alias gmur='git submodule update --rebase'
alias gmum='git submodule update --rebase'
alias gmd='git submodule deinit'
alias gms='git submodule status'
alias gmf='git submodule foreach '
alias gmfp='git submodule foreach "echo $path `git rev-parse HEAD``"'
